package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"math"
	"time"

	"github.com/couchcryptid/storm-data-graphql-api/internal/model"
)

// StormReports is the resolver for the stormReports field.
func (r *queryResolver) StormReports(ctx context.Context, filter model.StormReportFilter) (*model.StormReportResult, error) {
	reports, totalCount, err := r.Store.ListStormReports(ctx, &filter)
	if err != nil {
		return nil, err
	}

	byType, err := r.Store.CountByType(ctx, &filter)
	if err != nil {
		return nil, err
	}

	byState, err := r.Store.CountByState(ctx, &filter)
	if err != nil {
		return nil, err
	}

	byHour, err := r.Store.CountByHour(ctx, &filter)
	if err != nil {
		return nil, err
	}

	lastUpdated, err := r.Store.LastUpdated(ctx)
	if err != nil {
		return nil, err
	}

	var dataLagMinutes *int
	if lastUpdated != nil {
		lag := int(math.Round(time.Since(*lastUpdated).Minutes()))
		dataLagMinutes = &lag
	}

	return &model.StormReportResult{
		Reports:        reports,
		TotalCount:     totalCount,
		ByType:         byType,
		ByState:        byState,
		ByHour:         byHour,
		LastUpdated:    lastUpdated,
		DataLagMinutes: dataLagMinutes,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
